[package]
name = "imp"
version = "0.1.1"
authors = ["Niels Saurer <me@nielssaurer.com>"]
edition = "2018"

[[bin]]
name = "imp"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = { version = "0.19.6", features = ["lexer", "regex"] }
regex = "1"
z3 = "0.11.2"
egg = "0.6.0"
